name = "arenaix-engine"
main = "battle-engine.js"
compatibility_date = "2024-01-01"
compatibility_flags = ["nodejs_compat"]

[[d1_databases]]
binding = "DB"
database_name = "arenaix-db"
database_id = "da0c12f2-18cf-4a42-8fa7-5190fe857d10"

[[triggers]]
crons = ["*/2 * * * *"]

[vars]
SITE_URL = "https://arenaix.kryv.network"
